### PR TITLE
Added gtrendsR to suggests

### PR DESCRIPTION
**Pull request by JohnMcIntyreJR**

### CODE REVIEW

**Comment by csgillespie** [comment]
@JohnMcIntyreJR gtrendsR shouldn't be an import. This means that all course participants would need to install the package. It should be a suggests as it is only required for notes/slides

**Comment by JohnMcIntyreJR** [comment]
Okay. I tried putting it in suggests but still it was saying that there is no package called gtrendsR

**Comment by csgillespie** [comment]
Where did it say that?

**Comment by JohnMcIntyreJR** [comment]
If you have a look at my gitlab dev branch you'll be able to see the errors

**Comment by csgillespie** [comment]
Link?

**Comment by JohnMcIntyreJR** [comment]
https://gitlab.com/jumpingrivers-notes/r/jrIntroduction_notes/-/jobs/408940509

**Comment by JohnMcIntyreJR** [comment]
I think it should work when this travis check passes though

**Comment by csgillespie** [comment]
If you add gtrends to under suggests in the DESCRIPTION that error shouldn't happen

**Pull request merged**
